'use strict';
const express=require('express'),cors=require('cors'),axios=require('axios'),TTS=require('@google-cloud/text-to-speech'),Speech=require('@google-cloud/speech').v2;
const app=express(),tts=new TTS.TextToSpeechClient(),stt=new Speech.SpeechClient({apiEndpoint:'us-speech.googleapis.com'});
const voices={ko:{languageCode:'ko-KR',name:'ko-KR-Chirp3-HD-Aoede'},ja:{languageCode:'ja-JP',name:'ja-JP-Chirp3-HD-Aoede'}};
app.use(cors({origin:['https://waterfirst.github.io','http://localhost:8000']}));app.use(express.json({limit:'4mb'}));
app.get('/',(_q,r)=>r.json({status:'ok',tts:'Google Chirp 3: HD'}));
app.post('/interpret',async(q,r)=>{const{text,source,target}=q.body||{};if(!text||text.length>500||!voices[source]||!voices[target]||source===target)return r.status(400).json({error:'Invalid request'});try{const x=await axios.get('https://translate.googleapis.com/translate_a/single',{timeout:8000,params:{client:'gtx',sl:source,tl:target,dt:'t',q:text}});const translation=(x.data?.[0]||[]).map(v=>v?.[0]||'').join('').trim();if(!translation)throw Error('Empty translation');const[speech]=await tts.synthesizeSpeech({input:{text:translation},voice:voices[target],audioConfig:{audioEncoding:'MP3'}});r.json({translation,audioContent:Buffer.from(speech.audioContent).toString('base64')})}catch(e){console.error('Interpretation failed:',e.message);r.status(502).json({error:'Interpretation unavailable'})}});
app.post('/transcribe',async(q,r)=>{const{audio}=q.body||{};if(!audio)return r.status(400).json({error:'Audio required'});try{const project=process.env.GOOGLE_CLOUD_PROJECT;if(!project)throw Error('GOOGLE_CLOUD_PROJECT is missing');const[response]=await stt.recognize({recognizer:`projects/${project}/locations/us/recognizers/_`,config:{autoDecodingConfig:{},languageCodes:['auto'],model:'chirp_3',features:{enableAutomaticPunctuation:true}},content:Buffer.from(audio,'base64')});const result=response.results?.find(v=>v.alternatives?.[0]?.transcript);if(!result)return r.json({transcript:''});const transcript=result.alternatives[0].transcript.trim();const detectedLanguage=(result.languageCode||'ko-KR').startsWith('ja')?'ja':'ko';const targetLanguage=detectedLanguage==='ko'?'ja':'ko';const x=await axios.get('https://translate.googleapis.com/translate_a/single',{timeout:8000,params:{client:'gtx',sl:detectedLanguage,tl:targetLanguage,dt:'t',q:transcript}});const translation=(x.data?.[0]||[]).map(v=>v?.[0]||'').join('').trim();const[speech]=await tts.synthesizeSpeech({input:{text:translation},voice:voices[targetLanguage],audioConfig:{audioEncoding:'MP3'}});r.json({transcript,detectedLanguage,targetLanguage,translation,audioContent:Buffer.from(speech.audioContent).toString('base64')})}catch(e){console.error('Transcription failed:',e.message);r.status(502).json({error:'Transcription unavailable'})}});
app.listen(process.env.PORT||8080,()=>console.log('Interpreter API ready'));
